"""Print a Markdown table of the tools armguard-mcp registers, as an MCP client sees them.

Builds the server with the fake FR3 backend and the given policy (default: every tool group
enabled via examples/policies/fr3.yaml), lists the tools over an in-memory MCP session and
prints name, group, annotations, input parameters and the first sentence of the description.

    python scripts/gen_tool_table.py [--policy examples/policies/fr3.yaml]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import anyio
from mcp.client import Client

from armguard_mcp.backends.fake import FakeBackend
from armguard_mcp.policy import TOOL_GROUPS, load_policy
from armguard_mcp.safety.audit import AuditLogger
from armguard_mcp.server import build

ROOT = Path(__file__).resolve().parents[1]
GROUP_OF = {tool: group for group, tools in TOOL_GROUPS.items() for tool in tools}


def first_sentence(text: str) -> str:
    flat = " ".join(text.split())
    # Split at the first ". " that is not part of "e.g." / "i.e.".
    m = re.match(r"(.+?(?<!e\.g)(?<!i\.e)\.)(\s|$)", flat)
    return (m.group(1) if m else flat).replace("|", "\\|")


def hints(ann) -> str:
    if ann is None:
        return ""
    flags = []
    if ann.read_only_hint:
        flags.append("read-only")
    if ann.destructive_hint:
        flags.append("destructive")
    if ann.idempotent_hint:
        flags.append("idempotent")
    if ann.open_world_hint:
        flags.append("open-world")
    return ", ".join(flags)


def params(schema: dict) -> str:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    return ", ".join(f"`{p}`" if p in required else f"`{p}?`" for p in props) or "none"


async def main(policy_path: Path) -> None:
    policy = load_policy(policy_path)
    app = build(policy, FakeBackend.from_policy(policy), AuditLogger())
    async with Client(app.server, mode="auto") as client:
        tools = (await client.list_tools()).tools
    order = {t: i for i, t in enumerate(t for g in TOOL_GROUPS.values() for t in g)}
    tools.sort(key=lambda t: order.get(t.name, 999))
    print("| Tool | Group | Parameters | Annotations | Description |")
    print("|---|---|---|---|---|")
    for t in tools:
        print(
            f"| `{t.name}` | {GROUP_OF.get(t.name, '?')} | {params(t.input_schema)} | "
            f"{hints(t.annotations)} | {first_sentence(t.description or '')} |"
        )
    print(f"\n<!-- {len(tools)} tools, generated by scripts/gen_tool_table.py from {policy_path.name} -->")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--policy", type=Path, default=ROOT / "examples" / "policies" / "fr3.yaml")
    anyio.run(main, ap.parse_args().policy)
